FROM registry.ap-southeast-1.aliyuncs.com/dockerhub-mirrors/cuda:11.3.1-runtime-ubuntu20.04

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 \
    PATH=/opt/conda/bin:$PATH \
    TZ=Asia/Shanghai

RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
    GIT_CLONE="git clone --depth 10" && \
    cat /etc/apt/sources.list && \
    rm -rf /var/lib/apt/lists/* \
           /etc/apt/sources.list.d/cuda.list \
           /etc/apt/sources.list.d/nvidia-ml.list && \
    mirror_url=mirrors.bfsu.edu.cn && \
    sed -i "s/security.ubuntu.com/$mirror_url/" /etc/apt/sources.list && \
    sed -i "s/archive.ubuntu.com/$mirror_url/" /etc/apt/sources.list && \
    sed -i "s/security-cdn.ubuntu.com/$mirror_url/" /etc/apt/sources.list && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL ca-certificates tzdata git wget curl vim htop rsync psmisc unzip openssh-server dnsutils iputils-ping net-tools rsync lftp tmux && \
    apt-get clean

RUN ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone && \
    dpkg-reconfigure --frontend noninteractive tzdata

RUN wget https://dl.aaaazzzz.workers.dev/https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh -O ~/installer.sh && \
    /bin/bash ~/installer.sh -b -p /opt/conda && \
    rm ~/installer.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc && \
    find /opt/conda/ -follow -type f -name '*.a' -delete && \
    find /opt/conda/ -follow -type f -name '*.js.map' -delete && \
    CONDA_INSTALL="/opt/conda/bin/mamba install -y" && \
    $CONDA_INSTALL -c conda-forge pycocotools graphviz && \
    /opt/conda/bin/mamba clean -afy && \
    echo 'Conda Install Done!'

RUN PIP_INSTALL="/opt/conda/bin/pip --no-cache-dir install --upgrade -i https://mirrors.bfsu.edu.cn/pypi/web/simple" && \
    $PIP_INSTALL tfrecord scipy scikit-learn pandas numba scikit-image && \
    $PIP_INSTALL fvcore glances gpustat && \
    $PIP_INSTALL pyyaml pyhocon && \
    $PIP_INSTALL tensorboard requests jupyterlab && \
    $PIP_INSTALL mmcv mmcls mmdet mmsegmentation mmselfsup timm && \
    $PIP_INSTALL torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113 && \
    $PIP_INSTALL --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110 && \
    echo 'PIP Install Done!'

CMD ["sh","-c", "/opt/conda/bin/jupyter lab --no-browser --ip=0.0.0.0 --allow-root --notebook-dir='/code' --port=8888 --LabApp.token='' --LabApp.allow_origin='*' --LabApp.base_url=$OCTOPUS_JPY_BASE_URL"]