name: PyTorch Docker Image CI
on:
  push:
    tags:
    - v*
jobs:
    Dockerfile-1_7_0-py38-cu110-dali:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_USER}}/pytorch:1.7.0-py38-cu110-dali -f dockerfile/Dockerfile-1.7.0-py38-cu110-dali workspace
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_USER}}/pytorch:1.7.0-py38-cu110-dali
                docker logout
                docker login -u ${{secrets.ALIYUN_DOCKER_USER}} -p ${{secrets.ALIYUN_DOCKER_PASS}} registry.cn-hongkong.aliyuncs.com
                docker tag ${{secrets.DOCKER_USER}}/pytorch:1.7.0-py38-cu110-dali registry.cn-hongkong.aliyuncs.com/${{secrets.DOCKER_USER}}/pytorch:1.7.0-py38-cu110-dali
                docker push registry.cn-hongkong.aliyuncs.com/${{secrets.DOCKER_USER}}/pytorch:1.7.0-py38-cu110-dali
                docker logout registry.cn-hongkong.aliyuncs.com




