name: PyTorch Docker Image CI
on:
  push:
    tags:
    - v*
jobs:
    Dockerfile-1_10_0-py38-cu102:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_USER}}/pytorch:1.10.0-py38-cu102 -f dockerfile/Dockerfile-1.10.0-py38-cu102 workspace
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_USER}}/pytorch:1.10.0-py38-cu102


    Dockerfile-1_10_0-py38-cu102-dali:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_USER}}/pytorch:1.10.0-py38-cu102-dali -f dockerfile/Dockerfile-1.10.0-py38-cu102-dali workspace
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_USER}}/pytorch:1.10.0-py38-cu102-dali


    Dockerfile-1_10_0-py38-cu113:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_USER}}/pytorch:1.10.0-py38-cu113 -f dockerfile/Dockerfile-1.10.0-py38-cu113 workspace
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_USER}}/pytorch:1.10.0-py38-cu113


    Dockerfile-1_10_0-py38-cu113-dali:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Free disk space
              run: |
                df -h
                sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell
                sudo apt-get autoremove -y
                sudo apt-get clean
                sudo swapoff -a
                sudo rm -f /swapfile
                docker rmi $(docker image ls -aq)
                df -h
            - name: Build docker image
              run: docker build -t ${{secrets.DOCKER_USER}}/pytorch:1.10.0-py38-cu113-dali -f dockerfile/Dockerfile-1.10.0-py38-cu113-dali workspace
            - name: Deploy docker image
              run: |
                docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
                docker push ${{secrets.DOCKER_USER}}/pytorch:1.10.0-py38-cu113-dali

